export interface Branch {
  id: string;
  branchName: string;
  manager: string;
  address: string;
  phone: string;
  email: string;
}

export interface ProvinceGroup {
  id: string;
  province: string;
  branches: Branch[];
}

export const branchData: ProvinceGroup[] = [
  {
    id: "koshi",
    province: "Koshi Province",
    branches: [
      { id: "katahari", branchName: "Katahari Branch", manager: "Smiriti Kumari Majhi", address: "Katahari Rm-07, Morang", phone: "9857646263", email: "katahari57.cycnlbsl@gmail.com" },
      { id: "siddhicharan", branchName: "Siddhicharan Branch", manager: "Krishna Prasad Paudel", address: "Siddhicharan Mun-02, Okhaldhunga", phone: "9857646275", email: "Siddhicharan67.cycnlbsl@gmail.com" },
      { id: "illam", branchName: "Illam Branch", manager: "Upendra Yadav", address: "Illam Mun-04, Illam", phone: "9857646276", email: "Illam68.cycnlbsl@gmail.com" },
      { id: "pakhribas", branchName: "Pakhribas Branch", manager: "Rewati Raman Niraula", address: "Pakhribas Mun-07, Dhankuta", phone: "9857646280", email: "Pakhribas72.cycnlbsl@gmail.com" },
      { id: "damak", branchName: "Damak Branch", manager: "Pramila Basnet", address: "Damak Mun-01, Jhapa", phone: "9857646281", email: "Damak73.cycnlbsl@gmail.com" },
      { id: "triyuga", branchName: "Triyuga Branch", manager: "Sangita Rai", address: "Triyuga Mun-01, Udaypur", phone: "9857646282", email: "Triyuga74.cycnlbsl@gmail.com" },
      { id: "solu", branchName: "Solu Branch", manager: "Sujan Kathet", address: "Solu Dudhkunda Mun-04, Solukhumbu", phone: "9857646305", email: "solu82.cycnlbsl@gmail.com" },
      { id: "manebhanjyang", branchName: "Manebhanjyang Branch", manager: "Amita Bachan Sharma", address: "Manebhanjyang Mun-04, Okhaldhunga", phone: "9857646297", email: "manebhanjyang83.cycnlbsl@gmail.com" },
      { id: "phungling", branchName: "Phungling Branch", manager: "Dhurba Paudel", address: "Phungling Mun Ward No-03, Taplejung", phone: "9857646298", email: "phungling84.cycnlbsl@gmail.com" },
      { id: "phidim", branchName: "Phidim Branch", manager: "Khim Maya Sinjali", address: "Phidim Mun-03, Panchthar", phone: "9857646299", email: "phidim.cycnlbsl@gmail.com" },
      { id: "myanglung", branchName: "Myanglung Branch", manager: "Lekh Bahadur Khamcha", address: "Myanglung Mun-03, Terhathum", phone: "9857646300", email: "myanglung85.cycnlbsl@gmail.com" },
      { id: "bhojpur", branchName: "Bhojpur Branch", manager: "Nabin Rai", address: "Bhojpur Mun-06, Bhojpur", phone: "9857646301", email: "bhojpur86.cycnlbsl@gmail.com" },
      { id: "hilihang", branchName: "Hilihang Branch", manager: "Rina Kumari Kumal", address: "Hilihang Rm-05, Panchthar", phone: "9857646302", email: "hilihang87.cycnlbsl@gmail.com" },
      { id: "khandabari", branchName: "Khandabari Branch", manager: "Bhim Prasad Budhathoki", address: "Khandabari Mun-08, Sankhuwasabha", phone: "9857646303", email: "khandbari88.cycnlbsl@gmail.com" },
      { id: "diktel", branchName: "Diktel Branch", manager: "Babita Basnet", address: "Diktel Rupakot Mujuwagadhi Mun-05, Khotang", phone: "9857646304", email: "diktel89.cycnlbsl@gmail.com" },
      { id: "inaruwa", branchName: "Inaruwa Branch", manager: "Deepak Raj Nishad", address: "Inaruwa Mun-08, Sunsari", phone: "9857646309", email: "inaruwa99.cycnlbsl@gmail.com" },
    ],
  },
  {
    id: "madesh",
    province: "Madesh Province",
    branches: [
      { id: "ganeshman", branchName: "Ganeshman Branch", manager: "Ramesh Kumar Yadav", address: "Ganeshman Charnath Mun-01, Dhanusha", phone: "9857646255", email: "ganeshman49.cycnlbsl@gmail.com" },
      { id: "lalbandi", branchName: "Lalbandi Branch", manager: "Subodh Kumar Yadav", address: "Lalbandi Mun-08, Sarlahi", phone: "9857646261", email: "lalbandi55.cycnlbsl@gmail.com" },
      { id: "gaur", branchName: "Gaur Branch", manager: "Bivek Kumar Shah", address: "Gaur Mun-02, Rautahat", phone: "9857646245", email: "gaur66.cycnlbsl@gmail.com" },
      { id: "bardibas", branchName: "Bardibas Branch", manager: "Dev Sundar Mandal", address: "Bardibas Mun-05, Mahottari", phone: "9857646283", email: "Bardibas75.cycnlbsl@gmail.com" },
      { id: "birgunj", branchName: "Birgunj Branch", manager: "Sushil Prasad Yadav", address: "Birgunj MPC-17, Parsa", phone: "9857646287", email: "birgunj76.cycnlbsl@gmail.com" },
      { id: "golbazar", branchName: "Golbazar Branch", manager: "Pinky Chaudhary", address: "Siraha Mun-08, Golbazar", phone: "9857646343", email: "golbazar91.cycnlbsl@gmail.com" },
      { id: "rajbiraj", branchName: "Rajbiraj Branch", manager: "Jivach Yadav", address: "Saptari Mun-08, Rajbiraj", phone: "9857646344", email: "rajbiraj92.cycnlbsl@gmail.com" },
      { id: "bhawani", branchName: "Bhawani Branch", manager: "Devnath Patel", address: "Girabhawani Rm-03, Parsa", phone: "9857646346", email: "bhawani94.cycnlbsl@gmail.com" },
      { id: "nijgadh", branchName: "Nijgadh Branch", manager: "Ambikaesh Kumar Yadav", address: "Nijgadh Mun-11, Bara", phone: "9857646347", email: "nijgadh96.cycnlbsl@gmail.com" },
      { id: "durgabhagwati", branchName: "Durgabhagwati Branch", manager: "Santosh Prasad Sah", address: "Durgabhagwati Rm-4, Rautahat", phone: "9857646348", email: "durgabhagwati97.cycnlbsl@gmail.com" },
      { id: "bagmati-m", branchName: "Bagmati Branch", manager: "Ayan Mishra", address: "Bagmati Mun-5, Sarlahi", phone: "9857646349", email: "bagmati98.cycnlbsl@gmail.com" },
      { id: "pipara", branchName: "Pipara Branch", manager: "Suwan Kumar Rajbanshi", address: "Pipara Rm-07, Mahottari", phone: "9857646350", email: "pipara99.cycnlbsl@gmail.com" },
      { id: "kshireshwornath", branchName: "Kshireshwornath Branch", manager: "Nagendra Prasad Sah", address: "Kshireshwornath Mun-01, Dhanusha", phone: "9857646336", email: "kshireshwornath100.cycnlbsl@gmail.com" },
    ],
  },
  {
    id: "bagmati",
    province: "Bagmati Province",
    branches: [
      { id: "dhading", branchName: "Dhading Branch", manager: "Keshavraj Timilsina", address: "Nilkhantha Mun-03, Dhading", phone: "9857646201", email: "dhading32.cycnlbsl@gmail.com" },
      { id: "nuwakot", branchName: "Nuwakot Branch", manager: "Bishnu Prasad Ghimire", address: "Bidur Mun-08, Nuwakot", phone: "9857646236", email: "nuwakot33.cycnlbsl@gmail.com" },
      { id: "mugling", branchName: "Mugling Branch", manager: "Sudarshan Paudel", address: "Ichchha Kamana RM-06, Mugling", phone: "9857646235", email: "mugling34.cycnlbsl@gmail.com" },
      { id: "shami", branchName: "Shami Branch", manager: "Amrit Subedi", address: "Budhanilkhantha Mun-6, Kathmandu", phone: "9857646247", email: "shami40.cycnlbsl@gmail.com" },
      { id: "kalpavrikshya", branchName: "Kalpavrikshya Branch", manager: "Biva Roy", address: "Godawari Mun-9, Lalitpur", phone: "9857646246", email: "kalpavriksha41.cycnlbsl@gmail.com" },
      { id: "kanchan", branchName: "Kanchan Branch", manager: "Dipesh Majhi", address: "Choutara Sangachowkgadhi Mun-10, Sindhupalchok", phone: "9857646249", email: "kanchan43.cycnlbsl@gmail.com" },
      { id: "tamakoshi", branchName: "Tamakoshi Branch", manager: "Alina Pun", address: "Likhu Tamakoshi Rm-06, Ramechap", phone: "9857646257", email: "tamakoshi51.cycnlbsl@gmail.com" },
      { id: "golanjor", branchName: "Golanjor Branch", manager: "Devraj Giri", address: "Golanjor-06, Sindhuli", phone: "9857646262", email: "golanjor56.cycnlbsl@gmail.com" },
      { id: "patlekhet", branchName: "Patlekhet Branch", manager: "Mina Shrees", address: "Dhulikhel Mun-11, Kavrepalanchok", phone: "9857646264", email: "patlekhet58.cycnlbsl@gmail.com" },
      { id: "bhimeshwor", branchName: "Bhimeshwor Branch", manager: "Prasuna Pandit", address: "Bhimeshwor Mun-02, Dolakha", phone: "9857646265", email: "bhimeshwor59.cycnlbsl@gmail.com" },
      { id: "panauti", branchName: "Panauti Branch", manager: "Sandip Chamar", address: "Panauti Mun-09, Kavrepalanchok", phone: "9857646271", email: "panauti65.cycnlbsl@gmail.com" },
      { id: "thaha", branchName: "Thaha Branch", manager: "Mina Chaudhary", address: "Thaha Mun-04, Makwanpur", phone: "9857646294", email: "thaha82.cycnlbsl@gmail.com" },
      { id: "sudal", branchName: "Sudal Branch", manager: "Uma Devi Gautam", address: "Changunarayan Mun-08, Bhaktapur", phone: "9857646295", email: "sudal95.cycnlbsl@gmail.com" },
      { id: "kalika", branchName: "Kalika Branch", manager: "Chhand Prasad Aryal", address: "Kalika Mun-01, Ramche Rasuwa", phone: "9857646322", email: "kalika93.cycnlbsl@gmail.com" },
    ],
  },
  {
    id: "gandaki",
    province: "Gandaki Province",
    branches: [
      { id: "baglung", branchName: "Baglung Branch", manager: "Rajak Bishowkarma", address: "Baglung Mun-03, Baglung", phone: "9857646203", email: "baglung02.cycnlbsl@gmail.com" },
      { id: "khairenitar", branchName: "Khairenitar Branch", manager: "Dhirendra Pd Neupane", address: "Suklagandagi 7, Tanahun", phone: "9857646216", email: "khairenitar16.cycnlbsl@gmail.com" },
      { id: "hatiya", branchName: "Hatiya Branch", manager: "Radhika Thapa", address: "Galkot Mun-03, Hatiya", phone: "9857646204", email: "hatiya03.cycnlbsl@gmail.com" },
      { id: "besisahar", branchName: "Besisahar Branch", manager: "Bhoj Bahadur Lohar", address: "Besisahar Mun-07, Lamjung", phone: "9857646206", email: "besisahar05.cycnlbsl@gmail.com" },
      { id: "sundarbazar", branchName: "Sundarbazar Branch", manager: "Dipak Khatri", address: "Sundarbazar Mun-07, Lamjung", phone: "9857646207", email: "sundarbazar06.cycnlbsl@gmail.com" },
      { id: "kharbang", branchName: "Kharbang Branch", manager: "Yanu Buda Magar", address: "Badigaad RM-02, Kharbang", phone: "9857646208", email: "kharbang07.cycnlbsl@gmail.com" },
      { id: "burtibang", branchName: "Burtibang Branch", manager: "Rita Thapa", address: "Dhorpatan Mun-01, Burtibang", phone: "9857646209", email: "burtibang08.cycnlbsl@gmail.com" },
      { id: "kushmishera", branchName: "Kushmishera Branch", manager: "Sabitri Sharma", address: "Jaimini Mun-01, Kushmishera", phone: "9857646210", email: "kushmishera09.cycnlbsl@gmail.com" },
      { id: "belbagar", branchName: "Belbagar Branch", manager: "Tabita Thapa", address: "Jaimini Mun-08, Baglung", phone: "9857646222", email: "belbagar12.cycnlbsl@gmail.com" },
      { id: "bareng", branchName: "Bareng Branch", manager: "Narmaya Thapa", address: "Bareng RM-02, Baglung", phone: "9857646213", email: "bareng13.cycnlbsl@gmail.com" },
      { id: "acchete", branchName: "Acchete Branch", manager: "Jhalak Paudel", address: "Kanthekhola RM-02, Baglung", phone: "9857646214", email: "acchete14.cycnlbsl@gmail.com" },
      { id: "damauli", branchName: "Damauli Branch", manager: "Yubraj Gautam", address: "Vyas Mun-02, Tanahun", phone: "9857646215", email: "damauli15.cycnlbsl@gmail.com" },
      { id: "bhorletar", branchName: "Bhorletar Branch", manager: "Hemlal Shrees", address: "Madhyanepal Mun-06, Bhorletar", phone: "9857646218", email: "bhorletar18.cycnlbsl@gmail.com" },
      { id: "babiyachaur", branchName: "Babiyachaur Branch", manager: "Pabitra Pandit Bista", address: "Mangala RM-09, Babiyachaur", phone: "9857646228", email: "babiyachaur23.cycnlbsl@gmail.com" },
      { id: "galeshwor", branchName: "Galeshwor Branch", manager: "Sarada Rana", address: "Beni Mun-02, Galeshwor", phone: "9857646229", email: "galeshwor24.cycnlbsl@gmail.com" },
      { id: "huwas", branchName: "Huwas Branch", manager: "Krishna Kumari Bhusal Neupane", address: "Paiyun RM-4, Pabat", phone: "9857646231", email: "huwas26.cycnlbsl@gmail.com" },
      { id: "waling", branchName: "Waling Branch", manager: "Guma Basnet", address: "Waling Mun-9, Bhumre", phone: "9857646237", email: "waling29.cycnlbsl@gmail.com" },
      { id: "chhepeter", branchName: "Chhepeter Branch", manager: "Bishnu Gautam", address: "", phone: "9857646239", email: "chhepeter30.cycnlbsl@gmail.com" },
      { id: "kolhuwa", branchName: "Kolhuwa Branch", manager: "Puja Gotame", address: "Madhya Bindu Municipality", phone: "9857646238", email: "kolhuwa31.cycnlbsl@gmail.com" },
      { id: "jaljala", branchName: "Jaljala Branch", manager: "Aliza Lamsal", address: "Jaljala RM-03, Jaljala", phone: "9857646241", email: "jaljala35.cycnlbsl@gmail.com" },
      { id: "lahachok", branchName: "Lahachok Branch", manager: "Sabitri Shrestha", address: "", phone: "9857646242", email: "lahachok36.cycnlbsl@gmail.com" },
      { id: "pragatinagar", branchName: "Pragatinagar Branch", manager: "Dayaram Thapa", address: "Devchuli Mun-14, Pragatinagar", phone: "9857646243", email: "pragatinagar37.cycnlbsl@gmail.com" },
      { id: "sardi", branchName: "Sardi Branch", manager: "Rina Kumari Kumal", address: "", phone: "9857646244", email: "sardi38.cycnlbsl@gmail.com" },
      { id: "bhanubhakta", branchName: "Bhanubhakta Branch", manager: "Krishna Prasad Paudel", address: "", phone: "9857646249", email: "bhanubhakta53.cycnlbsl@gmail.com" },
      { id: "bayarghari", branchName: "Bayarghari Branch", manager: "Kabita Bhusal", address: "Bayarghari, Syangja", phone: "9857646320", email: "bayarghari113.cycnlbsl@gmail.com" },
      { id: "budhibazar", branchName: "Budhibazar Branch", manager: "Deepak Subedi", address: "Budhibazar, Kaski", phone: "9857646321", email: "budhibazar114.cycnlbsl@gmail.com" },
      { id: "galyang", branchName: "Galyang Branch", manager: "Saraswati Gautam Bhattarai", address: "Galyang, Syangja", phone: "9857646324", email: "galyang120.cycnlbsl@gmail.com" },
      { id: "gharpajhong", branchName: "Gharpajhong Branch", manager: "Sanjay Purja", address: "Gharpajhong Rm-02, Mustang", phone: "9857646227", email: "gharpajhong101.cycnlbsl@gmail.com" },
      { id: "chame", branchName: "Chame Branch", manager: "Subas Lal Karna", address: "Chame Rm-03, Manang", phone: "9857646323", email: "chame102.cycnlbsl@gmail.com" },
    ],
  },
  {
    id: "lumbini",
    province: "Lumbini Province",
    branches: [
      { id: "tamghas", branchName: "Tamghas Branch", manager: "Ganesh Chaudhary", address: "Resunga Mun-08, Gulmi", phone: "9857646205", email: "tamghas04.cycnlbsl@gmail.com" },
      { id: "shantipur", branchName: "Shantipur Branch", manager: "Prakash Regmi", address: "Chandrakot RM-04, Shantipur", phone: "9857646211", email: "shantipur10.cycnlbsl@gmail.com" },
      { id: "tansen", branchName: "Tansen Branch", manager: "Rima Ghatri", address: "Tansen Mun-02, Tansen", phone: "9857646212", email: "tansen11.cycnlbsl@gmail.com" },
      { id: "rampur", branchName: "Rampur Branch", manager: "Keshab Prasad Sharma", address: "Musikot 07, Gulmi", phone: "9857646217", email: "rampur17.cycnlbsl@gmail.com" },
      { id: "wami", branchName: "Wami Branch", manager: "Renu Khadka", address: "Musikot Mun-07, Wami", phone: "9857646219", email: "wami19.cycnlbsl@gmail.com" },
      { id: "purtighat", branchName: "Purtighat Branch", manager: "Dipendra Ghatri Magar", address: "Kaligandaki RM-04, Gulmi", phone: "9857646223", email: "purtighat20.cycnlbsl@gmail.com" },
      { id: "chhatragunj", branchName: "Chhatragunj Branch", manager: "Ajaya G.C", address: "Chatradev RM-05, Arghakhanchi", phone: "9857646224", email: "chhatragunj21.cycnlbsl@gmail.com" },
      { id: "simaltari", branchName: "Simaltari Branch", manager: "Dhanmaya Nepali", address: "Malika RM-08, Gulmi", phone: "9857646221", email: "simaltari22.cycnlbsl@gmail.com" },
      { id: "khaireni", branchName: "Khaireni Branch", manager: "Jagadish Raj Panta", address: "Satyawati RM-7, Gulmi", phone: "9857646230", email: "khaireni25.cycnlbsl@gmail.com" },
      { id: "bardaghat", branchName: "Bardaghat Branch", manager: "Ramesh Chaudhary", address: "Bardaghat Mun-07, Jimirebar", phone: "9857646232", email: "bardaghat27.cycnlbsl@gmail.com" },
      { id: "butwal", branchName: "Butwal Branch", manager: "Sapana Bhusal", address: "Butwal Sub-MP City-18, Rupandehi", phone: "9857646248", email: "butwal42.cycnlbsl@gmail.com" },
      { id: "banganga", branchName: "Banganga Branch", manager: "Chitra Sharma", address: "Banganga Mun-1, Kapilbastu", phone: "9857646250", email: "banganga44.cycnlbsl@gmail.com" },
      { id: "rapti", branchName: "Rapti Branch", manager: "Suresh Acharya", address: "Rapti RM-3, Dang", phone: "9857646251", email: "rapti45.cycnlbsl@gmail.com" },
      { id: "baijanath", branchName: "Baijanath Branch", manager: "Dharmaraj Rawat", address: "Baijanath Rural Mun-8, Banke", phone: "9857646252", email: "baijanath46.cycnlbsl@gmail.com" },
      { id: "ranipur", branchName: "Ranipur Branch", manager: "Tanka Bohara", address: "Thakurbaba Municipality-2, Bardiya", phone: "9857646254", email: "ranipur48.cycnlbsl@gmail.com" },
      { id: "ghorahi", branchName: "Ghorahi Branch", manager: "Birendra Bd. Karki", address: "Ghorahi SMPC-17, Dang", phone: "9857646288", email: "ghorahi77.cycnlbsl@gmail.com" },
      { id: "sainamaina", branchName: "Sainamaina Branch", manager: "Prakash Paudel", address: "Sainamaina, Rupandehi", phone: "071-440032", email: "sainamaina116.cycnlbsl@gmail.com" },
      { id: "gorusinge", branchName: "Gorusinge Branch", manager: "Bhikkhu Prasad Chaudhary", address: "Gorusinge, Kapilbastu", phone: "076-545027", email: "gorusinge117.cycnlbsl@gmail.com" },
      { id: "arunkhola", branchName: "Arunkhola Branch", manager: "Umesh Chaudhary", address: "Arungkhola, Nawalparasi", phone: "078-555321", email: "arunkhola121.cycnlbsl@gmail.com" },
      { id: "chhapiya", branchName: "Chhapiya Branch", manager: "Rabindra Kumar Mahoto", address: "Chhapiya, Rupandehi", phone: "9857646339", email: "chhapiya122.cycnlbsl@gmail.com" },
      { id: "odari", branchName: "Odari Branch", manager: "Krishna Yadav", address: "Odari, Kapilbastu", phone: "9857646328", email: "odari125.cycnlbsl@gmail.com" },
      { id: "bhalawari", branchName: "Bhalawari Branch", manager: "Ganga Godar Acharya", address: "Bhalawari, Rupandehi", phone: "071-561969", email: "bhawari126.cycnlbsl@gmail.com" },
      { id: "chutrabesi", branchName: "Chutrabesi Branch", manager: "Ram Bahadur G.C", address: "Chutrabesi, Arghakhanchi", phone: "9857646327", email: "chutrabeshi127.cycnlbsl@gmail.com" },
      { id: "belaspur", branchName: "Belaspur Branch", manager: "Mekh Raj Joshi", address: "Belaspur, Nawalparasi", phone: "9857646337", email: "bilaspur128.cycnlbsl@gmail.com" },
      { id: "dhekawar", branchName: "Dhekawar Branch", manager: "Gita Kumari Chaudhary", address: "Dhokawar, Rupandehi", phone: "9857646338", email: "dhokawor130.cycnlbsl@gmail.com" },
      { id: "bhoome", branchName: "Bhoome Branch", manager: "Janaki Badal", address: "Bhoome Rm-04, Western Rukum", phone: "9857646354", email: "bhoome108.cycnlbsl@gmail.com" },
      { id: "sunchhahari", branchName: "Sunchhahari Branch", manager: "Samak Thapa", address: "Sunchhahari Rm-04, Rolpa", phone: "9857646355", email: "sunchhahari109.cycnlbsl@gmail.com" },
      { id: "pratappur", branchName: "Pratappur Branch", manager: "Abhishek Chaudhary", address: "Pratappur 08, Nawalparasi", phone: "9857646233", email: "pratappur28.cycnlbsl@gmail.com" },
      { id: "khariboat", branchName: "Khariboat Branch", manager: "Kamana Rayamajhi", address: "Pyuthan Mun-09, Khariboat", phone: "9857646356", email: "khariboat110.cycnlbsl@gmail.com" },
    ],
  },
  {
    id: "karnali",
    province: "Karnali Province",
    branches: [
      { id: "prachandra", branchName: "Prachandra Branch", manager: "Tularam Thapa", address: "Khatyang Rm-04, Mugu", phone: "9857646256", email: "prachanda50.cycnlbsl@gmail.com" },
      { id: "sinja", branchName: "Sinja Branch", manager: "Janak Shahi", address: "Sinja Rm-02, Jumla", phone: "9857646260", email: "sinja54.cycnlbsl@gmail.com" },
      { id: "simta", branchName: "Simta Branch", manager: "Nagaendra Acharya", address: "Simta Rm-07, Surkhet", phone: "9857646266", email: "simta60.cycnlbsl@gmail.com" },
      { id: "raskot", branchName: "Raskot Branch", manager: "Bishnu Prasad Pangali", address: "Raskot Mun-06, Kalikot", phone: "9857646267", email: "raskot61.cycnlbsl@gmail.com" },
      { id: "lekhbeshi", branchName: "Lekhbeshi Branch", manager: "Srijana Sharma", address: "Lekhbeshi Mun-01, Surkhet", phone: "9857646270", email: "lekhbeshi64.cycnlbsl@gmail.com" },
      { id: "kalimati", branchName: "Kalimati Branch", manager: "Madanraj Awasthi", address: "Kalimati RM-02, Salyan", phone: "9857646290", email: "kalimati79.cycnlbsl@gmail.com" },
      { id: "birendranagar", branchName: "Birendranagar Branch", manager: "Hemraj Joshi", address: "Birendranagar Mun-12, Surkhet", phone: "9857646291", email: "birendranagar80.cycnlbsl@gmail.com" },
      { id: "thatikandh", branchName: "Thatikandh Branch", manager: "Sagar Shahi", address: "Thatikandh Rm-01, Dailekh", phone: "9857646332", email: "thatikandh103.cycnlbsl@gmail.com" },
      { id: "bheri", branchName: "Bheri Branch", manager: "Kalpana Thapa", address: "Bheri Mun-11, Jajarkot", phone: "9857646351", email: "bheri104.cycnlbsl@gmail.com" },
      { id: "chaurjahari", branchName: "Chaurjahari Branch", manager: "Begam Chand", address: "Chaurjhari Mun-07, Rukum Pashchim", phone: "9857646335", email: "chaurjhari105.cycnlbsl@gmail.com" },
      { id: "mudkechula", branchName: "Mudkechula Branch", manager: "Rajendra Bahadur Budha", address: "Mudkechula Rm-06, Dolpa", phone: "9857646352", email: "mudkechula106.cycnlbsl@gmail.com" },
      { id: "adanchuli", branchName: "Adanchuli Branch", manager: "Binod Pant", address: "Adanchuli Rm-03, Humla", phone: "9857646353", email: "adanchuli107.cycnlbsl@gmail.com" },
    ],
  },
  {
    id: "sudurpaschim",
    province: "Sudurpaschim Province",
    branches: [
      { id: "lamkichuha", branchName: "Lamkichuha Branch", manager: "Madan Singh Mahara", address: "Lamki Chuha Mun-2, Kailali", phone: "9857646253", email: "lamkichuha47.cycnlbsl@gmail.com" },
      { id: "bhimdatta", branchName: "Bhimdatta Branch", manager: "Janak Bdr Dhami", address: "Bhimdatta Mun-03, Kanchanpur", phone: "9857646258", email: "bhimdatta52.cycnlbsl@gmail.com" },
      { id: "mahakali", branchName: "Mahakali Branch", manager: "Janak Raj Joshi", address: "Mahakali Mun-04, Darchula", phone: "9857646268", email: "mahakali62.cycnlbsl@gmail.com" },
      { id: "patan", branchName: "Patan Branch", manager: "Padam Raj Pandeya", address: "Patan Mun-04, Baitadi", phone: "9857646269", email: "patan63.cycnlbsl@gmail.com" },
      { id: "panchadewal", branchName: "Panchadewal Branch", manager: "Dharmaraj Ghodasaini", address: "Panchadewal Binayak Mun-06, Accham", phone: "9857646293", email: "Panchadewal69.cycnlbsl@gmail.com" },
      { id: "belauri", branchName: "Belauri Branch", manager: "Khemraj Awasthi", address: "Belauri Mun-10, Kanchanpur", phone: "9857646278", email: "Belauri70.cycnlbsl@gmail.com" },
      { id: "amargadhi", branchName: "Amargadhi Branch", manager: "Ammar Bahadur Dhami", address: "Amargadhi Mun-07, Dadeldhura", phone: "9857646279", email: "Amargadhi71.cycnlbsl@gmail.com" },
      { id: "dipyal", branchName: "Dipyal Branch", manager: "Bimala Bhandari", address: "Dipyal Silgadi Mun-05, Doti", phone: "9857646289", email: "dipyal78.cycnlbsl@gmail.com" },
      { id: "jayprithivi", branchName: "Jayprithivi Branch", manager: "Rajendra Prasad Padhyay", address: "Jay Prithivi Mun-08, Bajhang", phone: "9857646292", email: "jayprithivi81.cycnlbsl@gmail.com" },
      { id: "melauli", branchName: "Melauli Branch", manager: "Manoj Bhat", address: "Melauli Mun-01, Haripur Baitadi", phone: "9857646325", email: "melauli111.cycnlbsl@gmail.com" },
      { id: "budhiganga", branchName: "Budhiganga Branch", manager: "Arjun Bdr Rawat", address: "Budhibanga Mun-03, Bajura", phone: "9857646357", email: "budhiganga112.cycnlbsl@gmail.com" },
    ],
  },
];

export const totalBranches = branchData.reduce((sum, p) => sum + p.branches.length, 0);
