export const provincesDistricts = [
  {
    id: "pradesh-1",
    name: "Province No. 1",
    districts: [
      "Jhapa",
      "Ilam",
      "Panchthar",
      "Taplejung",
      "Dhankuta",
      "Terhathum",
      "Sankhuwasabha",
      "Bhojpur",
      "Solukhumbu",
      "Okhaldhunga",
      "Khotang",
      "Udayapur",
      "Sunsari",
      "Morang",
    ],
  },
  {
    id: "pradesh-2",
    name: "Province No. 2",
    districts: [
      "Parsa",
      "Bara",
      "Rautahat",
      "Sarlahi",
      "Siraha",
      "Dhanusa",
      "Mahottari",
      "Jhapa",
    ],
  },
  {
    id: "bagmati",
    name: "Bagmati Pradesh",
    districts: [
      "Kathmandu",
      "Bhaktapur",
      "Lalitpur",
      "Kavre",
      "Sindhupalchok",
      "Nuwakot",
      "Rasuwa",
      "Dhading",
      "Makwanpur",
      "Rameechhap",
      "Dolakha",
    ],
  },
  {
    id: "gandaki",
    name: "Gandaki Pradesh",
    districts: [
      "Nawalpur",
      "Tanahun",
      "Lamjung",
      "Gorkha",
      "Manang",
      "Mustang",
      "Myagdi",
      "Parbat",
      "Syangja",
      "Kaski",
    ],
  },
  {
    id: "lumbini",
    name: "Lumbini Pradesh",
    districts: [
      "Kapilvastu",
      "Parasi",
      "Rupandehi",
      "Arghakhanchi",
      "Gulmi",
      "Palpa",
      "Nawalparasi",
      "Bardiya",
      "Dang",
      "Banke",
    ],
  },
  {
    id: "karnali",
    name: "Karnali Pradesh",
    districts: [
      "Jumla",
      "Dailekh",
      "Jajarkot",
      "Rukum West",
      "Rukum East",
      "Salyan",
      "Dolpa",
      "Dunuwa",
      "Surkhet",
      "Mugu",
      "Humla",
    ],
  },
  {
    id: "sudurpashchim",
    name: "Sudurpashchim Pradesh",
    districts: [
      "Doti",
      "Achham",
      "Bajura",
      "Bajhang",
      "Kailali",
      "Kanchanpur",
      "Dadeldhura",
      "Baitadi",
      "Udayapur",
    ],
  },
];

export const getDistrictsByProvince = (provinceId: string): string[] => {
  const province = provincesDistricts.find((p) => p.id === provinceId);
  return province ? province.districts : [];
};
